### ISSUE TITLE
Ability to map fields, not only properties

### ISSUE THREAD

**Issue by jeroko** [JoshClose/CsvHelper#416] opened 2015-08-18 15:34 UTC
I'd like to map some fields from my objects in order to write them to a csv, I wanted them to be inmutable, so I defined them as "public readonly", I can always change them to autoproperties with a private set, but they won't be inmutable anymore.

**Comment by Oxymoron290** [comment] 2015-08-18 17:44
I have this same issue.

**Comment by JoshClose** [comment] 2016-10-07 03:57
Duplicate of #408

**Closed by JoshClose** 2016-10-07 03:57 UTC
Labels: feature
