### ISSUE TITLE
Reference mismatch to System.Threading.Tasks.Extensions

### ISSUE THREAD

**Issue by mtissington** [JoshClose/CsvHelper#1488] opened 2020-03-28 19:53 UTC
Using 4.7.2

Not sure when this started but now we are getting the following and can no longer import any file.

`System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

File name: 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

File name: 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at CsvHelper.Configuration.CsvConfiguration..ctor(CultureInfo cultureInfo)`

**Comment by mtissington** [comment] 2020-03-28 20:12
Resolved - seems to have a dependency on nuget Microsoft System.Threading.Tasks.Extensions

**Comment by JoshClose** [comment] 2020-03-28 21:45
NuGet should add that for you. What version of CsvHelper?

**Comment by mtissington** [comment] 2020-03-28 21:50
That's what I thought - I'm using the latest version of CsvHelper and needed to add the Extensions manually.

**Comment by JoshClose** [comment] 2020-03-28 22:32
That's included for the 4.7 build. Maybe it's a fluke?

https://github.com/JoshClose/CsvHelper/blob/24d8d5393d1c88f852fec32803419bf5a800f2b9/src/CsvHelper/CsvHelper.csproj#L50

**Comment by mtissington** [comment] 2020-03-28 23:34
Hmm, i know it should but will it work for 4.7.2 also?

**Comment by donovan-ecargo** [comment] 2020-04-23 02:01
I'm experiencing the same issue.

Last working version is 13.0.0 for me, with the 4.7.2 .net . It is also the last one without the dependency on System.Threading.Tasks.Extensions.

My guess is that it's something going wrong with the dependency definition for the package

**Comment by imm-olate** [comment] 2020-07-22 03:24
I had the same issue running CsvHelper 15.0.5, it seemed to be an incompatibility with System.Test.Json 4.7.2. I had to downgrade System.Test.Json to 4.6.0.

**Comment by chucklu** [comment] 2020-11-05 10:29
I had the same issue but not using CsvHelper, I believed it can be fixed by the same solution. ProjectA referenced a custom libraryB.
I just checked the version of System.Threading.Tasks.Extensions under bin folder, find it's with the wrong verison 4.2.0.0.
Then I tried to scan the dependencies of my bin folder,  check which *.exe or *.dll depend on System.Threading.Tasks.Extensions, and print the library and the version of System.Threading.Tasks.Extensions
1
Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

2
System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

The above two libraries was used by libraryB, and when I check the nuget libraries list, I find libraryB depends on System.Threading.Tasks.Extensions with nuget version 4.5.4, which assembly version is 4.2.0.1

My solution is manually add System.Threading.Tasks.Extensions nuget reference in ProjectA directly.

**Comment by chucklu** [comment] 2020-11-05 10:34
And you will encounter another similar issue， which report the wrong version for "System.Runtime.CompilerServices.Unsafe", it's required 4.0.6.0 version, which mapped to nuget version 4.7.0. 
The solution is manually add System.Runtime.CompilerServices.Unsafe nuget reference with nuget version 4.7.0 in ProjectA directly.
https://stackoverflow.com/a/62770487/13338936
1
Microsoft.Extensions.Primitives, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

2
System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

3
System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

4
System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by chucklu** [comment] 2020-11-05 10:38
In conclusion, add the following two packages in Project directly(the project which reported the mismatch problem)
```xml
     <package id="System.Runtime.CompilerServices.Unsafe" version="4.7.0" targetFramework="net472" />
     <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net472" />
```

And the nuget should add the following bindingRedirect for you automatically in config file
```xml
   <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
      </dependentAssembly>
 <dependentAssembly>
       <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
       <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
      </dependentAssembly>
```

**Comment by JoshClose** [comment] 2020-11-16 16:31
There is another issue for this. Does this help? https://github.com/JoshClose/CsvHelper/issues/1462

**Comment by chrishildebran** [comment] 2020-11-17 22:58
@JoshClose, last week I had success employing a solution @MikeYeager suggested in issue #1462 (Closed), but today I'm yet again bit by this reference roundy-round. I've tried three times to replicate his solution with CSV v16, but it just keeps failing.  I've tried to make heads or tails of what the answer is, specifically @chucklu's, but I'm just spinning. Is there a bottom-line solution to this that will allow me to release with confidence?

**Comment by chucklu** [comment] 2020-11-18 05:16
@chrishildebran  Where did you encounter this issue?
1.on developed environment(local machine)？ You can provide me a repository which can reproduce it.
2.on deploy environment(test, staging, production)?  
3.And what's the exact error info you got? 
By the way, I did not have experience  about Azure.

**Comment by chrishildebran** [comment] 2020-11-18 14:49
@chucklu, im seeing this error during debuggin in Visual Studio. Cannot provide code. See attached collage of screenshots.
![CSV Helper Issue](https://user-images.githubusercontent.com/61524205/99545361-28a36080-296a-11eb-9d9e-953736c4c6d6.png)

**Comment by chrishildebran** [comment] 2020-11-18 14:52
I will say that reverting to a previously release's package config (CSV Helper 15.0.5, Microsoft.BCL.AsyncInterfaces 1.1.0, and System.Threading.Task.Extensions 4.5.2 is working. It would be nice to be able to upgrade without worrying though.

**Comment by chucklu** [comment] 2020-11-19 02:00
@chrishildebran  Please configure your visual studio, Tools-->Options-->Projects and Solutions-->Build And Run
Then set the output verbosity to detailed, rebuild your solution, then copy the ouput log and save it as a file, and upload it here.

If it's possible, could you zip your bin folder with the dll files and upload it here, I would like to analysis the dependency of all dll files.

**Comment by chucklu** [comment] 2020-11-19 02:12
> im seeing this error during debuggin in Visual Studio
Did you mean when you run the application directly, there is no problem? Then I guess it should be the problem of visual studio

**Comment by chucklu** [comment] 2020-11-19 08:40
@JoshClose  I find another version mismatch issue https://github.com/NuGet/Home/issues/10302, and it might be bug of nuget.
If nuget does not support auto detection feature, then we need to manually fix these issues.

**Comment by JoshClose** [comment] 2021-05-17 15:55
I changed all the references to exact version match. Between that and redirects, I think we should be good.

**Closed by JoshClose** 2021-05-17 15:55 UTC
Labels: bug

**Comment by JoshClose** [comment] 2021-11-23 21:19
In 27.2.1 I changed all the references to be >= the lowest version that CsvHelper needs. I changed the test project to use the latest version of every dependency and everything seems to work fine.

**Comment by dplabsindia** [comment] 2023-11-02 04:51
With target framework 4.7.2 the latest Stable Version of CSVHelper still lookin for the Microsoft.Bcl.AsyncInterfaces verison 1.0.0.0.  Even though the project contains Microsoft.Bcl.AsyncInterfaces  5.0.0.
Is There any alternative that CSVHelper should load 5.0.0 version as depenceny,

**Comment by chucklu** [comment] 2023-11-02 05:00
@dplabsindia  Do you have the bindingRedirect configuration in your app.config or web.config?
```xml  
<runtime>
	<assemblyBinding
		xmlns="urn:schemas-microsoft-com:asm.v1">
		<dependentAssembly>
			<assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
			<bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
		</dependentAssembly>
	</assemblyBinding>
</runtime>
```

**Comment by dplabsindia** [comment] 2023-11-02 05:53
> @dplabsindia Do you have the bindingRedirect configuration in your app.config or web.config?
> 
> ```
> <runtime>
> 	<assemblyBinding
> 		xmlns="urn:schemas-microsoft-com:asm.v1">
> 		<dependentAssembly>
> 			<assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
> 			<bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
> 		</dependentAssembly>
> 	</assemblyBinding>
> </runtime>
> ```

We have this in web.config. But still the problem persists. CSVhelper looking for assembly 1.0.0.0 of bcl asyncinteraces.

**Comment by chucklu** [comment] 2023-11-02 06:04
@dplabsindia It should not looking for assembly 1.0.0.0 of bcl asyncinteraces if you have the bindingRedirect in correct config file.
I am just wondering that you did not put the bindingRedirect at the correct place, might in a wrong config file, which you think it's correct one.

Please troubleshooting why your project try to locate assembly 1.0.0.0 of bcl asyncinteraces by using [Fuslogvw.exe](https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer#view-details-about-a-specific-failure)
[View details about a specific failure](https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer#view-details-about-a-specific-failure)  according this, you should get the detail about why the bindingRedirect does not work for you. From my experience, most time you just configure the wrong file


https://github.com/awaescher/Fusion  this tool is better than Microsoft provided Fuslogvw.exe

**Comment by chucklu** [comment] 2023-11-06 03:07
@dplabsindia  Any feedback about the bindingRedirect issue? Have you located the root cause with tool Fusion++ written by awaescher?

**Comment by dplabsindia** [comment] 2023-11-07 19:39
> @dplabsindia Any feedback about the bindingRedirect issue? Have you located the root cause with tool Fusion++ written by awaescher?

Not able to use this tool. But I am sure, we have multiple app.config files and one web.config file. The reference is everywhere when we install the package. I can see the bindingRedirect every .config file. Still the csvhelper complaining and looking for the 1.0.0.0 version.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=XXXXX' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)\nFile name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=XXXXXX'\n

**Comment by chucklu** [comment] 2023-11-08 02:31
@dplabsindia  why can't you use Fusion++ tool? do you work on windows? maybe you can try the tool [Fuslogvw.exe](https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer#view-details-about-a-specific-failure) provided by Microsoft

**Comment by dplabsindia** [comment] 2023-11-09 20:24
> @dplabsindia why can't you use Fusion++ tool? do you work on windows? maybe you can try the tool [Fuslogvw.exe](https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer#view-details-about-a-specific-failure) provided by Microsoft

The tool expects SDK on the server. And several other permission issues for now. Meanwhile, I have gone through the 
<ItemGroup Condition="'$(TargetFramework)' == 'net47'">
	<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.1.0" />
	<PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.0" />
	<PackageReference Include="Microsoft.CSharp" Version="4.5.0" />
	<PackageReference Include="System.Buffers" Version="4.5.1" />
	<PackageReference Include="System.Memory" Version="4.5.4" />
	<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.2" />
</ItemGroup>

in thread, https://github.com/JoshClose/CsvHelper/issues/1597#issuecomment-840672638 .

Assuming that by default the 4.7.2 target framework is looking for the 1.0.0.0 which is the runtime error as it is not able to find this version.

All config files as the binding redirect,

 <dependentAssembly>
        <assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>

 
Not sure of these but somewhere the redirect binding failed due to something.
 
Any help in this
