### ISSUE TITLE
Line end is not recognized when it's "\r\n" and FieldReader.bufer ends on "\r"

### ISSUE THREAD

**Issue by qqqwwweeea** [JoshClose/CsvHelper#677] opened 2017-05-08 12:02 UTC
If FieldReader.bufer's last symbol is "\r" from line ending "\r\n" then "\n" is ignored and this line end is treated like a field value meaning that csvhelper tries to parse "\r" and fails
Save this text to file using "\r\n" line ending and try to read it

```
Id;Date;Cycles;Hours
1;2100-12-31 ;;
2;;;
3;2100-12-31 ;;
4;;;
5;2100-12-31 ;;
6;;;
7;2100-12-31 ;;
8;;;
9;2100-12-31 ;;
10;;;
11;2100-12-31 ;;
12;;;
13;2100-12-31 ;;
14;;;
15;2100-12-31 ;;
16;;;
17;2100-12-31 ;;
18;;;
19;2100-12-31 ;;
20;;;
25;;;
26;;;
27;;;
28;2012-02-13 ;;
29;2012-02-13 ;;
30;2012-02-13 ;;
31;2012-02-13 ;;
32;;;
33;;;
34;;;
35;;;
36;;;
37;;;
38;;;
39;;;
40;;;
41;;;
42;;;
43;;;
44;;;
45;;;
46;;;
47;;;
48;;;
49;;;
50;;;
51;;;
52;;;
53;;;
54;;;
55;2010-01-04 ;;
56;2010-01-04 ;;
57;2010-01-04 ;;
58;2010-01-04 ;;
59;2010-01-04 ;;
60;2010-01-04 ;;
61;;;
62;;;
63;2003-07-12 ;;
64;;;
65;;;
66;;;
67;;;
68;;;
69;;;
70;;;
71;;;
72;;;
73;;;
74;;;
75;;;
76;;;
77;2009-06-21 ;;
78;2009-06-21 ;;
79;2009-06-21 ;;
80;2009-06-21 ;;
81;2009-06-21 ;;
82;2009-06-21 ;;
83;2009-06-21 ;;
84;2009-06-21 ;;
85;2009-06-21 ;;
86;2009-06-21 ;;
87;2009-06-21 ;;
88;2009-06-21 ;;
89;2009-06-21 ;;
90;2009-06-21 ;;
91;2009-06-21 ;;
92;;;
93;;;
94;;;
95;;;
96;;;
97;;;
98;;;
99;;;
100;;;
101;;;
102;;;
103;;;
104;2004-06-30 ;;
105;2004-06-30 ;;
106;2004-02-29 ;;
107;;;
108;2004-02-01 ;;
109;;;
110;2003-09-30 ;;
111;;;
112;;;
113;;;
114;;;
115;;;
116;;;
117;;;
118;;;
119;;;
120;;7550;
121;;7341;
122;;;
123;;;
124;;;
125;;;
126;;;
127;;;
128;;;
129;;;
130;;;
131;;;
132;;;
133;;;
134;;;
135;;;
136;;;
137;;;
138;;;
139;;;
140;;;
141;;;
142;;;
143;;;
144;;;
145;;;
146;;;
147;;;
148;;;
149;;;
150;;;
151;;;
152;;;
153;;;
154;;;
155;;;
156;;;
157;2100-12-31 ;;
158;2100-12-31 ;;
159;2100-12-31 ;;
160;2100-12-31 ;;
161;2100-12-31 ;;
162;2100-12-31 ;;
163;2100-12-31 ;;
164;2100-12-31 ;;
165;2100-12-31 ;;
166;2100-12-31 ;;
167;2100-12-31 ;;
168;2100-12-31 ;;
169;2100-12-31 ;;
170;2100-12-31 ;;
171;2100-12-31 ;;
172;2100-12-31 ;;
173;2100-12-31 ;;
174;2100-12-31 ;;
175;2100-12-31 ;;
176;2100-12-31 ;;
177;2100-12-31 ;;
178;2100-12-31 ;;
179;2100-12-31 ;;
180;2100-12-31 ;;
181;2100-12-31 ;;
182;2100-12-31 ;;
183;2100-12-31 ;;
184;2100-12-31 ;;
185;2100-12-31 ;;
186;2100-12-31 ;;
187;2100-12-31 ;;
188;2100-12-31 ;;
189;2100-12-31 ;;
190;2100-12-31 ;;
191;2100-12-31 ;;
192;2100-12-31 ;;
193;2100-12-31 ;;
194;2100-12-31 ;;
195;2100-12-31 ;;
196;2100-12-31 ;;
197;2100-12-31 ;;
198;2100-12-31 ;;
199;2100-12-31 ;;
200;2100-12-31 ;;
201;2100-12-31 ;;
202;2100-12-31 ;;
203;2100-12-31 ;;
204;2100-12-31 ;;
205;2100-12-31 ;;
206;2100-12-31 ;;
207;2100-12-31 ;;
208;2100-12-31 ;;
209;2100-12-31 ;;
210;2100-12-31 ;;
211;2100-12-31 ;;
212;2100-12-31 ;;
213;2100-12-31 ;;
214;2100-12-31 ;;
215;2100-12-31 ;;
216;2100-12-31 ;;
217;2100-12-31 ;;
218;2100-12-31 ;;
219;2100-12-31 ;;
220;2100-12-31 ;;
221;2100-12-31 ;;
222;2100-12-31 ;;
223;2100-12-31 ;;
224;2100-12-31 ;;
225;2100-12-31 ;;
226;2100-12-31 ;;
227;2100-12-31 ;;
228;2100-12-31 ;;
229;2100-12-31 ;;
230;2100-12-31 ;;
231;2100-12-31 ;;
232;2100-12-31 ;;
233;2100-12-31 ;;
234;2100-12-31 ;;
235;2100-12-31 ;;
236;2100-12-31 ;;
237;2100-12-31 ;;
238;2100-12-31 ;;
239;2100-12-31 ;;
240;2100-12-31 ;;
241;2100-12-31 ;;
242;2100-12-31 ;;
243;2100-12-31 ;;
244;2100-12-31 ;;
245;2100-12-31 ;;
246;2100-12-31 ;;
247;2100-12-31 ;;
248;2100-12-31 ;;
249;2100-12-31 ;;
250;2100-12-31 ;;
251;2100-12-31 ;;
252;2100-12-31 ;;
253;2100-12-31 ;;
254;2100-12-31 ;;
255;2100-12-31 ;;
256;2100-12-31 ;;
257;2100-12-31 ;;
258;2100-12-31 ;;
259;2100-12-31 ;;
260;2100-12-31 ;;
261;2100-12-31 ;;
262;2100-12-31 ;;
263;2100-12-31 ;;
264;2100-12-31 ;;
265;2100-12-31 ;;
266;2100-12-31 ;;
267;2100-12-31 ;;
268;2100-12-31 ;;
269;2100-12-31 ;;
270;2100-12-31 ;;
271;2100-12-31 ;;
272;2100-12-31 ;;
273;2100-12-31 ;;
274;2100-12-31 ;;
275;2100-12-31 ;;
276;2100-12-31 ;;
277;2100-12-31 ;;
278;2100-12-31 ;;
279;2100-12-31 ;;
280;2100-12-31 ;;
281;2100-12-31 ;;
282;2100-12-31 ;;
283;2100-12-31 ;;
284;2100-12-31 ;;
285;2100-12-31 ;;
286;2100-12-31 ;;
287;2100-12-31 ;;
288;2100-12-31 ;;
```
```
var csv = new CsvReader(new StringReader(fileContent), new CsvConfiguration
            {
                CultureInfo = CultureInfo.InvariantCulture,
                Delimiter = ";",
                ThrowOnBadData = true,
                IgnoreReferences = true,
                WillThrowOnMissingField = false
            });


public class Class1
    {
    public long Id { get; set; }
        public DateTime? Date { get; set; }
        public int? Cycles { get; set; }
        public int? Hours { get; set; }
    }
```

**Comment by JoshClose** [comment] 2017-05-08 14:11
What version are you using?

**Comment by qqqwwweeea** [comment] 2017-05-08 14:22
Sorry, forgot to mention
It's 3.0.0-beta-7

**Comment by JoshClose** [comment] 2017-05-08 15:28
Does this not work for you?

```cs
void Main()
{
	var stream = new MemoryStream();
	var writer = new StreamWriter(stream);
	var reader = new StreamReader(stream);

	var config = new CsvConfiguration
	{
		BufferSize = 6
	};
	var csv = new CsvParser(reader, config);
	
	writer.Write("1,2,3\r\n");
	writer.Write("4,5,6\r\n");
	writer.Flush();
	stream.Position = 0;
	
	csv.Read().Dump();
	csv.Read().Dump();
}
```

I get:
```
["1", "2", "3"]
["4", "5", "6"]
```

With the `BufferSize` set to 6, it should be ending the buffer on the first `\r`.

**Comment by qqqwwweeea** [comment] 2017-05-09 08:32
Your example works for me.
But!
I was in a hurry and forgot to add one important detail - the last field should be missing
Here is the complete code that throws exception

```
using System.Globalization;
using System.IO;
using System.Linq;
using CsvHelper;
using CsvHelper.Configuration;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            var reader = new StreamReader(stream);

            var config = new CsvConfiguration
            {
                CultureInfo = CultureInfo.InvariantCulture,
                Delimiter = ";",
                ThrowOnBadData = true,
                IgnoreReferences = true,
                WillThrowOnMissingField = false,
                HasHeaderRecord = false,
                BufferSize = 6
            };
            var csv = new CsvReader(reader, config);

            writer.Write("1;22;\r\n");
            writer.Write("4;55;\r\n");
            writer.Flush();
            stream.Position = 0;

            var ssss = csv.GetRecords<Class1>().ToArray();

        }
    }

    public class Class1
    {
        public int A { get; set; }
        public int B { get; set; }
        public int? C { get; set; }
    }
}
```

**Comment by jamesbascle** [comment] 2017-05-24 03:28
@JoshClose

This is the exact issue that I ran into that I sent you the file for.  I think I have a fix ready... let me prepare it for a PR.

**Comment by JoshClose** [comment] 2017-05-24 16:08
Are you able to reproduce this where the buffer size only goes to the end of the first line? I'm having trouble doing that.

**Comment by jamesbascle** [comment] 2017-05-24 16:11
Huh. Hadn't thought of trying that. Do you have the code?

On May 24, 2017 12:08 PM, "Josh Close" <notifications@github.com> wrote:

Are you able to reproduce this where the buffer size only goes to the end
of the first line? I'm having trouble doing that.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/JoshClose/CsvHelper/issues/677#issuecomment-303772352>,
or mute the thread

**Comment by JoshClose** [comment] 2017-05-24 16:12
I was wrong... I can. I wasn't seeing the `\r` at the end.

This only appears to happen if your field has quotes around it also.

**Comment by jamesbascle** [comment] 2017-05-24 16:13
Ah, yeah.  That seems accurate, since most of the files i use happen to not hjave quotes, i would have expected something by now to trigger this.

**Comment by JoshClose** [comment] 2017-05-24 16:16
This fails.

```cs
[TestMethod]
public void Test1()
{
	var s = new StringBuilder();
	s.Append( "1,\"2\"\r\n" );
	s.Append( "3,4\r\n" );
	var config = new CsvConfiguration
	{
		BufferSize = 6
	};
	using( var reader = new StringReader( s.ToString() ) )
	using( var parser = new CsvParser( reader, config ) )
	{
		var row = parser.Read();
		Assert.IsFalse( row[1].EndsWith( "\r" ) );
	}
}
```

**Comment by JoshClose** [comment] 2017-05-25 17:52
Fix is merged and release chi03 is on NuGet.

**Closed by JoshClose** 2017-05-25 17:52 UTC
