### ISSUE TITLE
How can I map the row number using attributes, rather than a full map class?

### ISSUE THREAD

**Issue by SniderThanYou** [JoshClose/CsvHelper#1451] opened 2020-02-04 13:54 UTC
Hi Josh!

I'm looking at your answer to https://github.com/JoshClose/CsvHelper/issues/845. How can I accomplish the same thing using attributes? Here's what I tried:

```C#
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,Name");
        writer.WriteLine("1,one");
        writer.WriteLine("2,two");
        writer.Flush();
        stream.Position = 0;
        
        csv.Configuration.RegisterClassMap<TestMap>();
        csv.GetRecords<Test>().ToList().Dump();
    }
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
    [TypeConverter(typeof(RowNumberConverter))]
    public int RowNumber { get; set; }
}

class RowNumberConverter : DefaultTypeConverter
{
    public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
    {
        return row.Context.Row;
    }
}
```

This generates a `HeaderValidationException`. If I set `csv.Configuration.HeaderValidated = null;`, then it generates a `MissingFieldException`.  If I set `csv.Configuration.MissingFieldFound = null;`, then no errors are generated, but also each `RowNumber` is just zero. If I set a breakpoint in the `RowNumberConverter`, that line is never hit.

Thanks Josh!

**Comment by AltruCoder** [comment] 2020-02-04 20:17
I don't really like it, but I found if you add a `DefaultAttribute` to `RowNumber`, along with setting `HeaderValidated` and `MissingFieldFound` to `null`, you can get it to work.
```csharp
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,Name");
        writer.WriteLine("1,one");
        writer.WriteLine("2,two");
        writer.Flush();
        stream.Position = 0;
        
        csv.Configuration.HeaderValidated = null;
        csv.Configuration.MissingFieldFound = null;

        csv.GetRecords<Test>().ToList().Dump();
    }
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
    [Default("1")]
    [TypeConverter(typeof(RowNumberConverter))]
    public int RowNumber { get; set; }
}

class RowNumberConverter : DefaultTypeConverter
{
    public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
    {
        return row.Context.Row;
    }
}
```

**Comment by JoshClose** [comment] 2020-02-07 15:48
I think there should be a way to do this. Maybe adding something like a `ConvertUsingAttribute` that would take in a type interface that could be called.

**Comment by SniderThanYou** [comment] 2020-02-07 18:31
Hey David, great workaround! I'll stick with a dedicated mapping class for now, but I appreciate your efforts.

Josh, I'm glad to hear that you agree. I look forward to the solution! Thanks for maintaining this great tool.

**Comment by JoshClose** [comment] 2021-04-20 19:36
My suggestion was identical to @AltruCoder's, so I'm going to close this.

**Closed by JoshClose** 2021-04-20 19:36 UTC
Labels: feature

**Comment by ajtruckle** [comment] 2022-01-21 13:14
What about exposing such a field under the hood via a configuration setting? To me it sounds sensible to allow easy access to a row number in the text file by design. Maybe that is too complicated! Anyway, thanks for this working method which I will adopt.
