### ISSUE TITLE
Empty DataTable when setting HasHeaderRecord = false

### ISSUE THREAD

**Issue by dmitriy-shleht** [JoshClose/CsvHelper#1240] opened 2019-02-20 21:21 UTC
Hi
I'm trying to read the csv, but as soon as I set `HasHeaderRecord = false`, then I get an empty table.
_version:12.1.2_

```
1,one,yes,a
2,two,no,b
```

```
using (var reader = new StreamReader("d:\\text.txt"))
using (var csv = new CsvReader(reader, new Configuration{ Delimiter=",", Encoding = Encoding.UTF8, HasHeaderRecord = false}))
{
	using (var dr = new CsvDataReader(csv))
	{
		var dt = new DataTable();
		dt.Load(dr);
		//the table is empty
	}
}
```

**Comment by facundofarias** [comment] 2019-03-06 11:45
Same issue here. Any ideas @dmitriy-shleht ?

**Comment by Alexey-Stolyarov** [comment] 2019-03-06 16:34
Looks like currently there is no way to create IDataReader based on csv without header and read first row:
```
public CsvDataReader(CsvReader csv)
{
    this.csv = csv;

    csv.Read();

    if (csv.Configuration.HasHeaderRecord)
    {
        csv.ReadHeader();
    }
    else
    {
        skipNextRead = true;
    }
}
```

**Comment by JoshClose** [comment] 2019-03-11 03:02
I'll add this as a feature.

**Comment by twilsonxpert** [comment] 2019-03-11 19:19
In fact, it doesn't return any rows at all.

https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper.Tests/DataTableTests/CsvDataReaderTests.cs#L133

**Comment by twilsonxpert** [comment] 2019-03-11 22:36
I think the key here is that CsvDataReader.GetSchemaTable() doesn't add any rows if csv.Configuration.HasHeaderRecord is false.

**Comment by jack-guide** [comment] 2019-06-25 07:34
I am getting the same issue - the table is empty when HasHeaderRecord = false

do you know when a fix for this will be released?

thanks

**Comment by enmaku** [comment] 2019-07-01 18:43
Also unable to use this lib because of this error. Will have to switch libs if not resolved soon, which is a shame because I really like this one.

Fix incoming?

**Comment by enmaku** [comment] 2019-07-01 18:47
Also, returning an empty dataset when a reasonable configuration option is set to false is adequately unexpected behavior that this should definitely be considered a bug. This really isn't a feature request no matter how you spin it. This is a bug and marking it as a feature request deprioritizes work on it unnecessarily.

**Comment by kmidhunmathew** [comment] 2020-05-06 19:17
Have we got any solution for this??

**Comment by kmidhunmathew** [comment] 2020-05-06 19:21
> I'll add this as a feature.

Any update on this?

**Comment by FoolishWiseman** [comment] 2020-08-15 21:07
18 months later, still an issue.

**Comment by ASCSolution** [comment] 2021-03-31 03:33
Any update on this?

**Comment by sfst-from-sf** [comment] 2021-06-28 11:40
> For interim, I wrote the following to use the CsvHelper without a header row to return a DataTable. 
>It does create columns with just the index as the name. Open to better solutions until a fix is implemented.

Thank you! I almost gave up switching to a different library when I found [your useful comment](https://github.com/JoshClose/CsvHelper/issues/1240#issuecomment-530891840).

[https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers](https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers) gives a nice overview about many CSV parsers and their performance, but not functional capability.

[..]
> 			for (int i = 0; i < csv.Context.Record.Length; i++)

But I had to add "Parser." at 3 places, e.g.:
 			for (int i = 0; i < csv.Context.Parser.Record.Length; i++)

**Comment by ronnysolheim** [comment] 2022-08-09 07:49
I have the same problem. Any fix comming?

**Comment by kurtnelle** [comment] 2022-09-16 23:32
I have the same problem. It's a showstopper as well. Any fix? Perhaps a reasonable work around?

**Comment by dwing73** [comment] 2023-04-18 13:42
I can see the PR for this work is still in peer review state. 
Is there any news on when this may be reviewed @JoshClose ?

**Comment by JoshClose** [comment] 2024-01-24 22:28
Fixed.

**Closed by JoshClose** 2024-01-24 22:28 UTC
Labels: feature
