### ISSUE TITLE
Error with CsvWriter with the version 27 and NetStandard project

### ISSUE THREAD

**Issue by GuillaumeCorneau** [JoshClose/CsvHelper#1798] opened 2021-05-11 12:40 UTC
Hi,

I tried to update CSVHelper to the latest version (27.0.2) to my NetStandard project and I got an error when I try to use the CSVWriter.
This is the error I receive
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception de HRESULT : 0x80131040)
CSVHelper install Microsoft.Bcl.AsyncInterfaces v5.00 but if I force to install the version 1.1.1, everything is ok.
.NetFramework project seems to be work even if I use Microsoft.Bcl.AsyncInterfaces v5.00.

Could you check on your side if you have the same issue than me ?

Steps to reproduce
1. Create new NetStandard project
2. Install CSVHelper
3. Create this function
`		
public void TestFunction()
		{
            StringBuilder sb = new StringBuilder();
            var write = new StringWriter(sb);
            CsvConfiguration cfg = new CsvConfiguration(CultureInfo.InvariantCulture);
            CsvWriter writer = new CsvWriter(write, cfg);
		}`

4. Call the function on program start by exemple

You will get the error

**Comment by JoshClose** [comment] 2021-05-12 21:20
Duplicate of #1798

**Closed by JoshClose** 2021-05-12 21:20 UTC
Labels: bug
