### ISSUE TITLE
Please stop bumping major version so frequently

### ISSUE THREAD

**Issue by prcdpr** [JoshClose/CsvHelper#1757] opened 2021-03-31 15:55 UTC
I like the library but release cycle is flawed in my opinion. CSV library should be pretty mature after a couple of iterations instead of bumping major version sometimes a couple of times per month.

**Comment by JoshClose** [comment] 2021-03-31 15:59
I'm going off semantic versioning so any breaking change to the API, which includes behavior, gets a major version bump.

The library should work fine in any set of major versions, so there is nothing requiring you to upgrade. You'd only need to upgrade if there are features you want in the newer versions.

**Comment by JoshClose** [comment] 2021-04-01 17:52
I suppose this is a symptom of keeping the library very open. I try to make it so anything in the system can be replaced, but that also means that some obscure method that no one will ever use gets another parameter added to it and it causes a major version bump.

I could close up the system and make everything private/internal and it would solve a lot of these major version bumps. I think a lot of people would not like though.

I've been looking into doing a pipeline system where you can add/modify/remove any piece of the system. That would allow me to close parts of the system because you'd be able to easily change behavior without me having to modify interfaces and method signatures to allow for some simple feature request.

Most of the breaking changes wouldn't affect anyone. There was a major one recently though with configuration which affected everyone, but those types of changes don't happen often. I used to wait and built up all the breaking changes into the next release, but that made it so a release only happened once or twice a year. People were upset that a feature took a year to be implemented.

What is your personal issue with this? Are you updating and finding that your code doesn't compile anymore?

**Comment by kemsky** [comment] 2021-05-21 15:06
@JoshClose, the problem is that after each couple of version bumps it feels like a totally new library. You have made your changes once but then it is multiplied at least a thousand times because developers have to adjust their code. 

There is even more, developer opens the changelog for v19 -> v20 upgrade and see:

```
...
All IReaderConfiguration setters removed
..removed
removed
removed
removed
...
```

Ok, cool, so what should the developer do? There is no help, no migration path. Many hours must be lost for a rewrite.

I'm not going to argue anymore, this was a good lesson for us, but strongly suggest watching Spec-ulation Keynote by Rich Hickey.

**Comment by JoshClose** [comment] 2021-05-21 15:26
> Ok, cool, so what should the developer do? There is no help, no migration path. Many hours must be lost for a rewrite.

That reminds me that I'm going to make a migration section in the docs to explain what needs to be done on major version bumps. I should do that soon.

> strongly suggest watching Spec-ulation Keynote by Rich Hickey

I'll take a look at this.

**Comment by JoshClose** [comment] 2021-05-21 16:50
The Spec-ulation Keynote by Rich Hickey was interesting. 

Never making a breaking change seems good for something like the .NET Framework, but doing that on a small library like this would be more of a pain I think. For many changes I would have to have released a `CsvHelper2` package and everyone would have to switch to that instead. That's a nightmare to maintain and I think would be confusing for users. Now there are 2 packages, 2 documentation sites, etc. Next time there is a major change there would be `CsvHelper3` and more things to manage. Maybe it's possible to rename lower level things or namespace things instead. That would be a good thing to think about for future changes. 

I'm one person that does this for free on my spare time. If this were a paid project with a team of people, releasing a new package and documentation for breakages like .NET does for major releases, would be feasible. I think have a migration section in the docs will have to be a compromise. I can definitely try and do workarounds for major things.

If many people are really not liking the major bumps, I may just close the system up. By that I mean, making lots of classes `internal`, removing all the interfaces, remove all the `virtual` modifiers, etc. This is mostly why there are major bumps. I think people like that flexibility though... but maybe I'm wrong.

**Comment by AltruCoder** [comment] 2021-05-24 18:00
@JoshClose  I may be wrong, but I don't think Rich Hickey was advocating for a CsvHelper2.  I think he was advocating to _never_ have a breaking change.  Anytime you want to introduce something new that would break things, you change the name of the method and leave the old method there.  You deprecate the old method and users can upgrade to the new method on their own time and not have to worry about an upgrade breaking the code they already have.

**Comment by JoshClose** [comment] 2021-05-24 18:15
@AltruCoder Yes. I guess I wasn't clear enough. I believe some of the changes wouldn't be able to work like that and would require a new version released. For instance, the `CsvReader` and `CsvWriter` constructors taking a config, and the config is now `readonly`. This would either require a new class `CsvReader2`, or a new constructor, deprecating the old version of either. This doesn't mean people won't use it. The reason for this change is due to random weird threading issues that was only solved by making the config immutable. What do you in this case? I don't want people to ever use the old deprecated class/constructor. The only option then is to create a whole new library.

Any time an interface changes, it's a breaking change. I could create an `IReaderConfiguration2`, but then anything that implements it would need a new version. Any other class/interface that uses it would also need a new version. Basically, interfaces would just destroy things.

This is why I said at the end that for something even close to this is to happen in this library, I would have to make a lot of changes removing all of the flexibility of the library. This would actually make my life a lot easier, and people that don't like major version bumps. Other people that like being able to hack the library a little when they want to change something wouldn't be too happy.

This is why I thought migration documentation along with trying to adhere to some of these rules, would be a good compromise. If I did want to stick to never making a breaking change, I would definitely want to start a new library and from a clean slate.

**Comment by JoshClose** [comment] 2021-05-24 18:25
I'm open to anything I guess. If people want no breaking changes, but want features implemented immediately, I could deprecate things and have an ongoing beta version of the next library that is "use at your own risk because there will be breaking changes before the final release". When there is enough features implemented and I think the library is stable enough, I could release `CsvHelper2`. The previous version would only get bug fixes then. I don't want to be in the game of maintaining 2 libraries. Everyone would need to migrate to `CsvHelper2`. 

I don't see how this is any different than just saying major bumps are breaking changes. 

If a library has no breaking changes, would there ever be a major version bump?

Would `CsvHelper2` start on version 1 or 2? I would assume 2. Since CsvHelper is already on v27, I would probably need to change the name of the library and start fresh.

**Comment by AltruCoder** [comment] 2021-05-24 18:36
I can see where you are coming from that you don't want users to use some of the older methods because of issues that are fixed with the breaking changes.  But if you can mark them as deprecated, why they were deprecated, and what they should be using instead,  I would think most users would make their way to the newer (better) methods. 

> If a library has no breaking changes, would there ever be a major version bump?
I believe that was his point.  No more major changes.  Your version could be something more like the date created, rather than 14.1.0 which doesn't really tell you that much about it.  CsvHelper, for example was on the same major version for a long time and then suddenly jumped numerous major versions in a matter of months.

**Comment by AltruCoder** [comment] 2021-05-24 18:53
It's a different way to think about software updates.  I'm not saying it couldn't come with it's own set of problems. However, I do think it is a frustration for a number of users when their code keeps breaking with the rapid succession of major versions coming from the CsvHelper project.

**Comment by JoshClose** [comment] 2021-05-24 18:57
> I do think it is a frustration for a number of users when their code keeps breaking with the rapid succession of major versions coming from the CsvHelper project.

There were probably only 2 versions from 3 to 27 that would break normal usage.

> Your version could be something more like the date created, rather than 14.1.0 which doesn't really tell you that much about it.

I'm guessing NuGet wouldn't be able to handle that. I suppose it could handle 2021.05.24.x properly though, so maybe that would be fine.

> CsvHelper, for example was on the same major version for a long time and then suddenly jumped numerous major versions in a matter of months.

That's because I was waiting for a bunch of changes for a major bump. People had their feature implemented, but had to wait up to a year to use it. Yes, no breaking changes would eliminate the wait for them.

Maybe I should create a new library. There would need to be some major changes to allow for no breaking changes.

- No breaking changes.
- Releases are dates.
- No interfaces.
- No virtual methods.
- No read only properties.
- Classes will use properties for construction. If a constructor arg is needed for something that is required, it would need to be a single parameter class object so properties can be added to it.
- Or all constructor properties are named with defaults.
- All classes are sealed.
- Most classes are internal.
- It could handle other file types like fixed-width.

This would actually make my life a lot better because I could force behavior. There would be much less questions. Less bugs.

I would need some people to ask questions about the API, features, etc. @StefanBertels would be one. He's pretty busy and probably already annoyed with me. ;)

What do you think of that idea?

**Comment by StefanBertels** [comment] 2021-05-24 19:40
Hi. Busy might be, but not annoyed. 

IMHO we cannot demand a really stable version from some free / voluntary open source library like this. There always can be changes and some might be breaking (or making them non-breaking might be a big overhead) -- even for a helper library readings CSV files. We all like it if useful features are implemented, the library is fast, uses state-of-the art API, .NET versions etc....

We should keep in mind that even minor updates _might_ break things (maybe just new or even fixed bugs). I really wish there would be some attribute (similar to `[Obsolete]`) that could be used to mark features that might change (`[NonStableFeature]`) which would mean: Major version bump only if stable features change. Would make life easier for users if they just use common (stable) features.

What I really dislike are breaking changes that do not cause compiler errors.

Regarding inheritance: I personally try to avoid inheritance and would not miss virtual methods, or unsealed classes. There are better options to add features (adding thing to processing pipelines). 

Regarding Joshs list: I suggest to make things immutable (readonly) where feasible/possible and maybe pass a parameter class object to a constructor to allow adding new things (or deprecating old ones).

**Comment by JoshClose** [comment] 2021-05-24 21:10
The pipeline would definitely allow for things to be changed more easily without breaking stuff.

I'd like to make a lot of those changes in the currently library... but that would probably make everyone mad. The pipeline would be another breaking change, but would allow for less in the future.

I kinda like the idea of starting from scratch. Create an API and make it flexible and changeable without needing breaking changes. It would be a lot easier to add in other parsers too. Or maybe that's version 28.

**Comment by TimSirmovics** [comment] 2021-05-24 22:15
I don't think anyone really expects a free OS library to never have breaking changes, the problem has just been exacerbated by a recent run of breaking changes with a lot of major version increments. Generally I think most people are comfortable with a new major version of a library containing breaking changes, just not so frequently and not so many changes.

I think your idea of closing up the library is good, but with Pipelines so people like myself who have done a lot of extra development on top of it can continue to use it.

I don't see the need for a CsvHelper2. I think if you could introduce pipelines and run a pre-release version for a few months where we could test and provide PR's and feedback, eventually you could release this as a v28 and the major version should be fairly stable from there.

I know you have a discussion feature open for Pipelines (https://github.com/JoshClose/CsvHelper/discussions/1738), I will try to have a think about any up-front design considerations but certainly if we could work with a pre-release version I could provide useful feedback.

**Comment by JoshClose** [comment] 2021-05-24 22:31
@TimSirmovics I like this idea. I can close up the system and make sure it still works for people that need to change/extend things.

I'd also like some input on changes to add in a fixed-width parser. The parser is the easy part. The configs, context, mappings, etc are what make it difficult. I believe most of the CsvReader/CsvWriter API is generic for any set of rows/fields, but most of the internals are different. Maybe there could be a more generic reader. Maybe there is a `FixedWidthPipeline` that is used instead and that's all that is needed.

**Comment by JoshClose** [comment] 2021-05-24 22:34
Version 28 could also start versioning by date instead since 2021 > 28. :)

**Comment by TimSirmovics** [comment] 2021-05-24 22:36
I have written a few fixed width parsers so happy to provide feedback there as well.

**Comment by JoshClose** [comment] 2021-05-24 22:52
> I find the date releases mainly good for companies who have a scheduled monthly/quarterly/annual release.

Oh I'm never going to do that.

**Comment by jzabroski** [comment] 2022-11-02 14:33
I think this issue should be closed.  I like the frequent updates and fast fixes, personally.  Just because a feel people complain loudly about something doesn't mean there is something wrong.  A lot of people just hate change and work to do.  They want a free library with free maintenance cost.  Sorry, it doesnt work like that.

**Comment by JoshClose** [comment] 2022-11-02 15:35
I'm not planning on changing for the time being. Most breaking changes people won't even notice.

**Closed by JoshClose** 2022-11-02 15:35 UTC
Labels: bug

**Comment by jzabroski** [comment] 2022-11-02 17:36
I will add, for users that want to spend their time complaining about this, in addition to writing integration tests, consider creating a service to abstract away CsvHelper as a dependency.  As a consultant, I have seen codebases where people have `new CsvHelper.CsvConfiguration()` everywhere!  I guess it's Josh's fault if people write terribly repetitive code, and we can reference Rich Hickey's Spec-ulation talk as support for being a rote engineer who copy-pastes things everywhere with no regard to maintainability.  I might sound harsh, but the end goal is to make you a better engineer.  I would not want to work with someone who just writes mindless code and creates a giant maintenance nightmare.
