### ISSUE TITLE
Validate csv file

### ISSUE THREAD

**Issue by Cezus** [JoshClose/CsvHelper#657] opened 2017-03-16 09:45 UTC
Hello,

Maybe this is a feature request. Is it possible to validate a csv file with a simple statement? Like:

```
csvReader = new CsvReader(textReader);
// [Omitted Configuration settings]
var validationResult = csvReader.Validate();
return validationResult.IsValid;
```

With kind regards,

Cees van Altena

**Comment by jamesbascle** [comment] 2017-03-16 14:36
You could just do a try catch on GetRecords<dynamic>()

**Comment by Cezus** [comment] 2017-03-28 13:35
Thank you for the fast reply!

> You could just do a try catch on GetRecords<dynamic>()

It is something but I would like to call this a work-around. For the user it is better to use a Validate() method or something like that because when you advise another way to validate, we developers have to change our code.

Please also add the work-around to the docs.

With kind regards,

**Comment by JoshClose** [comment] 2017-03-28 13:51
What would it be validating?

**Comment by Cezus** [comment] 2017-03-28 14:55
Hmm good one. If the string/file/stream is in a CSV format?

**Comment by JoshClose** [comment] 2017-03-28 21:04
I'm not even sure if that's possible. Worst case scenario is the entire file is one row with a single field.

There is some bad field detection happening currently. There are config options for `ThrowOnBadData` and `BadDataCallback` that can be used.

**Comment by JoshClose** [comment] 2017-04-23 05:41
I'm going to close this for now. If you can think of a way to validate a file I'll look into. The issue is a bad formatted file could like a file with a single row and field, and that's valid.

**Closed by JoshClose** 2017-04-23 05:41 UTC

**Comment by Cezus** [comment] 2017-04-24 09:54
> I'm going to close this for now. If you can think of a way to validate a file I'll look into. The issue is a bad formatted file could like a file with a single row and field, and that's valid.

No problem, sorry for not responding.

**Comment by sagarkbhatt** [comment] 2019-07-25 11:30
+1 for this feature
