### ISSUE TITLE
DetectColumnCountChanges causing exception even when IgnoreReadingExceptions is set

### ISSUE THREAD

**Issue by SaroTasciyan** [JoshClose/CsvHelper#501] opened 2016-03-21 20:50 UTC
I am not quite sure if this a bug or an expected behaviour. With **IgnoreReadingExceptions** set, I wasn't expecting reading operation to break unless something inevitable due to parsing process happens. However, a change in number of columns breaks reading when **DetectColumnCountChanges** is set.

What I'm trying to achieve is basicly read a file to the end (streaming), process each row containing expected number of columns, log the rows that do not. Rows with missing fields are logged via **ReadingExceptionCallback** but _rows with extra fields_ breaks reading operation instead of being logged via callback.

So, I went for a horrible workaround disabling **DetectColumnCountChanges** and using **ShouldSkipRecord** as follows:
 ```c#
private static bool ShouldSkipRecord(string[] fieldValues)
{
    if (fieldValues.Length == ModelMapping.FieldCount) { return false; }
 
    string rawData = String.Join(Seperator, fieldValues);
    Console.WriteLine("Skipping row with unexpected column count. Raw data: {0}", rawData);

    return true;
}
```

In my opinion an option like **WillThrowOnMissingFields** for extra fields would be awsome

**Comment by JoshClose** [comment] 2016-10-05 04:01
This is fixed in version 3.0. If `DetectColumnCountChanges` is on and the count changes but `IgnoreReadingExceptions` is on, you'll get the callback now.

**Closed by JoshClose** 2016-10-05 04:01 UTC

**Comment by SaroTasciyan** [comment] 2016-10-05 07:43
@JoshClose Thank you for fixing this issue and letting us know. However, it has been a lifetime so I had to implement my own workaround in my previous company. I do not maintain the project anymore but I'm just curious why this issue wasn't labeled/commented as bug. I was really considering about fixing this and creating a PR back then. 
Just to let you know, thanks.

**Comment by JoshClose** [comment] 2016-10-05 14:07
This was a duplicate of another issue. I have been really busy and wasn't able to put any time into this project, is the reason it took so long. I've spent nearly every night of the past 2 months going through the backlog though, and I'll be through everything fairly soon here.
