### ISSUE TITLE
Exception classes are not marked as serializable

### ISSUE THREAD

**Issue by tl24** [JoshClose/CsvHelper#466] opened 2015-12-14 22:20 UTC
Having an issue when we try and use CsvHelper library as part of our seed code for EntityFramework.  The exceptions aren't marked as serializable, so we don't get the actual exception from the CsvHelper library if there is an issue when running a migration.

Getting this error:
Type 'CsvHelper.TypeConversion.CsvTypeConverterException' in assembly 'CsvHelper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' is not marked as serializable.

**Comment by JoshClose** [comment] 2015-12-14 22:35
I'll add this. http://stackoverflow.com/a/100369/68499

**Comment by xgao2** [comment] 2016-02-29 20:39
I got this error too. Then I found out that was caused by the csv file itself. Try to create a new csv file without any format and see if that works. You should be able to see the content of the csv file in the VS after you add it to the project.

**Comment by corfor** [comment] 2016-06-08 16:57
I got this error too.

Type 'CsvHelper.CsvReaderException' in assembly 'CsvHelper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' is not marked as serializable.

**Comment by JoshClose** [comment] 2016-06-08 17:17
I will try and get to this tonight. This should be a simple change.

**Comment by JoshClose** [comment] 2016-06-09 02:11
Version 2.15.0.0 is on NuGet and the attribute is there for all the exceptions.

**Closed by JoshClose** 2016-06-09 02:11 UTC
Labels: feature

**Comment by pinaki1234** [comment] 2017-03-27 07:21
Hello I have installed CSVHELPER from Nuget and in references it is showing version 2.0.0.0 but still I get this error:
Type 'CsvHelper.Configuration.CsvConfigurationException' in assembly 'CsvHelper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' is not marked as serializable.
What is the resolution? Thanks

**Comment by JoshClose** [comment] 2017-03-27 15:42
That class apparently isn't. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvConfigurationException.cs

Log this as a new issue, and I'll assign it as a bug.
