### ISSUE TITLE
Write dynamic objects

### ISSUE THREAD

**Issue by benfoster** [JoshClose/CsvHelper#187] opened 2013-08-09 10:46 UTC
Is it possible to write an `IEnumerable<dynamic>`. The following code throws an exception "No properties are mapped for System.Object":

            var foos = new List<dynamic>();
            dynamic obj = new ExpandoObject();
            obj.Foo = "Bar";
            foos.Add(obj);

            var ms = new MemoryStream();
            using (var sw = new StreamWriter(ms))
            {
                using (var writer = new CsvWriter(sw))
                {
                    writer.WriteRecords(foos);
                }
            }

**Comment by damiangreen** [comment] 2015-09-14 16:31
I've managed to write lists of expandos, like so:

 public static IEnumerable<dynamic> ToExpandoList(this List<object[]> results, List<string> columns)
        {
            foreach (var item in results)
            {
                IDictionary<string, object> expando = new ExpandoObject();
                for (var i = 0; i < columns.Count; i++)
                {
                    expando.Add(columns[i], item[i]);
                }
                yield return ((dynamic)expando);
            }
        }

 public static MemoryStream GenerateCsv(IEnumerable records, List<string> columnNames)
        {
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            var csv = new CsvWriter(writer);
           
            columnNames.ForEach(item => csv.WriteField(item));
            
            csv.NextRecord();
           
            foreach (var item in records)
            {
                foreach (var v in (IDictionary<string, object>)item)
                {
                    csv.WriteField(v.Value);
                }
                csv.NextRecord();
            }
            writer.Flush();
            stream.Flush();
            stream.Position = 0;
            return stream;
        }
....
using (var reader = cmd.ExecuteReader())
                    {
                        var columns = reader.GetColumnNames();
                        var results = DataReaderExtensions.Read(reader).ToList();
                        var list = results.ToExpandoList(columns);
                        return GenerateCsv(list, columns);
                    }

Jsut in case this helps anyone until this functionality is incorporated

**Comment by ravensorb** [comment] 2016-08-21 19:43
Its been a few years :)  Any update on this?

**Comment by JoshClose** [comment] 2016-08-22 17:51
No. :( I'm making this project more of a priority now though so I can get through some of these major features that have been around for a while. Unfortunately, stuff like this tends to take a lot of hours to do.

**Comment by JoshClose** [comment] 2016-08-26 05:19
This is turning out to be a really difficult thing to do. The problem is, you can do anything based on the type, but it doesn't mean anything. You need to have the object itself. This doesn't work with reflection and there aren't any `PropertyInfo`s, so the whole structure of how CsvHelper works doesn't really apply. The code is also very ugly because there needs to be `#if !NET_2_0 && !NET_3_5 && !PCL` directives all over the place. If it was just `ExpandoObject`, it wouldn't be so bad, but I need to work with `IDynamicMetaObjectProvider` instead.

I found a way to pull the data here. http://stackoverflow.com/a/14011692/68499 This still has the issues I stated above.

I'm working through it, but it'll probably take a few days at least. Hopefully I can come up with something that is somewhat clean.

**Comment by JoshClose** [comment] 2016-08-26 19:16
I found a way that isn't horrible to look at. This feature will be in version 3.0.0-beta2 on NuGet.

**Closed by JoshClose** 2016-08-26 19:16 UTC
Labels: feature

**Comment by mayconbeserra** [comment] 2017-01-23 14:06
Hi @JoshClose , is there any documentation for writing the csv based on a list of dynamic objects?

I haven't seen anything in the documentation.

Regards,

**Comment by JoshClose** [comment] 2017-01-23 18:55
Not yet, but it should work like any other type of object. Are you having some issues with it?

**Comment by CheeseNPort** [comment] 2017-03-30 09:53
Josh, thanks for this, I was also looking at writing ExpandoObjects to Csv's and having installed version 3.0.0 beta 7 it all worked well!! I tried to install the latest which was beta 8 but got a Nuget error saying it wasn't compatible with .Net version 4.5.2.

I would have suggested using the Dynamitey package which is brilliant for getting a list of dynamic properties and their values from a dynamic object but as you've sorted it, I don't really mind how it works! :)

Great library, thanks for this.

**Comment by CheeseNPort** [comment] 2017-03-30 10:02
And @mayconbeserra, using version 3.0.0 beta 7, I just called the code as normal i.e.

`
public byte[] GetCsvFile()
        {
            dynamic Expando1 = new ExpandoObject();
            Expando1.Foo1 = "Bar1";
            Expando1.Foo2 = "Bar2";

            dynamic Expando2 = new ExpandoObject();
            Expando2.Foo1 = "Bar3";
            Expando2.Foo2 = "Bar4";

            List<dynamic> ListToExport = new List<dynamic>()
            {
                Expando1,
                Expando2
            };

            using (MemoryStream Ms = new MemoryStream())
            {
                using (StreamWriter Sw = new StreamWriter(Ms))
                {
                    CsvWriter OutputCsv = new CsvWriter(Sw);
                    OutputCsv.WriteRecords(ListToExport);
                }
                return Ms.ToArray();
            }
        }
`

**Comment by JoshClose** [comment] 2017-03-30 14:30
So, can I ask what your use case for .NET 4.5.2 is? Why are you using that over 4.6?

I switched to VS2017 and removed all project types except netstandard1.3. Here is a chart of what that supports. https://github.com/dotnet/standard/blob/master/docs/versions.md

If it's a common case to need < 4.6 for new development, I'll add back in 4.0 support or something. My thought is new development would be >= 4.6 or core. Legacy development could use CsvHelper 2.x.

**Comment by CheeseNPort** [comment] 2017-03-30 14:33
Fortunately I am in a position to upgrade to 4.6 without any problem's so I'll do that. No reason, just because that was the version when the project was created,

**Comment by pwen090** [comment] 2017-07-18 23:31
One reason supporting older .NET might be helpful is I believe that Mono currently maps to .NET 4.5 for support. So it might be helpful in being compatible with Mono which helps to be able to use the code across OSX and Linux. I could be missing some Mono/.NET 4.6 compatibility nuance so apologies in advance!

**Comment by JoshClose** [comment] 2017-07-19 14:46
Xamarin can use .NET Core. https://blog.xamarin.com/net-standard-library-support-for-xamarin/

Are you talking about something else?

**Comment by pwen090** [comment] 2017-07-19 18:26
Mono is a bit different than Xamarin. The default Mono project targets .NET 4.5. I just tested a Mono project with CsvHelper and you can properly add and use CsvHelper 2.16.3. But when you try to add the latest beta it gives an error because the package does not target .NET 4.5 etc... There might be some way to leverage the net standard beta version of CsvHelper within a Mono project but I am not sure. I will let you know if I figure out a way but just wanted to mention it.

**Comment by work-des** [comment] 2017-08-14 09:28
The problem with writing a dynamic object was not solved.

```
dynamic Expando1 = new ExpandoObject();
            Expando1.Foo1 = "Bar1";
            Expando1.Foo2 = "Bar2";

            dynamic Expando2 = new ExpandoObject();
            Expando2.Foo1 = "Bar3";
            Expando2.Foo2 = "Bar4";

            List<dynamic> ListToExport = new List<dynamic>()
            {
                Expando1,
                Expando2
            };

            using (MemoryStream Ms = new MemoryStream())
            {
                using (StreamWriter Sw = new StreamWriter(Ms))
                {
                    CsvWriter OutputCsv = new CsvWriter(Sw);
                    OutputCsv.WriteRecords(ListToExport);
                }
                return Ms.ToArray();
            }
```
Exception
> Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?

**Comment by sintetico82** [comment] 2019-06-10 15:46
Hi, I am using the 2.16.3
In which version is it possible to use IDictionary<string, object>?

**Comment by JoshClose** [comment] 2019-06-10 18:05
Use it how? Does this pertain to dynamic objects?

**Comment by mishal153** [comment] 2022-10-17 01:53
Looking for ways to map the dynamic properties to names of their own. seems related and impossible to do at the moment.

**Comment by JoshClose** [comment] 2022-10-17 19:48
@mishal153 Do you want to use `dynamic` types or are do you want to create a map at runtime?
