### ISSUE TITLE
CoreCLR Support

### ISSUE THREAD

**Issue by shrayasr** [JoshClose/CsvHelper#469] opened 2015-12-21 04:53 UTC
Hey, 

At the outset, I'd like to thank you for taking time out to write this really nifty and clean library. Its my go to lib of choice for CSV handling on C#. 

Just wanted to know if you have anything on the roadmap for porting CsvHelper to CoreCLR? 

Cheers :beers:

**Comment by JoshClose** [comment] 2015-12-21 18:09
Yes. A few other people have requested it also. I was originally going to wait until the final release, but too many people have requested, so I'll probably do it before that.

**Comment by neris** [comment] 2016-01-24 23:10
:+1:
I really want this feature. CsvHelper and NLog are only two libraries that my project depends on that don't have .NET Core support.

**Comment by GeertvanHorrik** [comment] 2016-02-02 08:17
Duplicate of #415?

**Comment by juswes** [comment] 2016-04-12 13:42
@JoshClose Any update on when this library will also work with asp.net core? Really like this library and hoping to use it in my asp.net core projects.

**Comment by JoshClose** [comment] 2016-04-13 02:26
Soon. Hopefully within a week.

**Comment by juswes** [comment] 2016-04-13 05:44
That is great to hear. Then I will pospone my csv implementation for now. Many thanks for all the great work you have been doing and sharing with others.

**Comment by JoshClose** [comment] 2016-04-17 03:16
Version 2.14.0.0 has been published to NuGet and contains CoreCLR support. Let me know if you run into any issues.

**Closed by JoshClose** 2016-04-17 03:16 UTC
