### ISSUE TITLE
WillThrowOnMissingField doesn't throw when later row shorter than first row

### ISSUE THREAD

**Issue by dennisverheijen** [JoshClose/CsvHelper#579] opened 2016-09-20 10:12 UTC
(using CsvHelper 2.16.3) I have a file that looks like this:

```
A;B;C;D
1;2
E;F;G;H
```
I have defined a mapping for column index 0 and 2.
When I read this file using the code below, I expect that the ReadingExceptionCallback is called for row 2, but it isn't. It seems to work OK when the first row is the shorter row.
Background: I want to use the Reading Exceptions to skip records when a MAPPED field is missing in a row. If an unmapped field is missing in a row, e.g. column 3, the row is acceptable. I can't use DetectColumnCountChanges because that will fail the whole file.

```
...
            var csvReaderConfig = new CsvConfiguration()
            {
                Delimiter = ";",
                HasHeaderRecord = false,
                DetectColumnCountChanges = false,
                IgnoreReadingExceptions = true,
                WillThrowOnMissingField = true,
                ReadingExceptionCallback = <callback>,
                CultureInfo = CultureInfo.InvariantCulture,
                IsHeaderCaseSensitive = false,
                SkipEmptyRecords = false,
                TrimFields = true,
                TrimHeaders = true,
                IgnoreBlankLines = true
            };
...

using (var streamReader = _readerSource.GeTextReader(absoluteInputFilePath))
{
    var csvReader = new CsvReader(streamReader, csvReaderConfig);
    csvRecords = csvReader.GetRecords<CsvRecord>().ToList();
}
```
Please advise

**Comment by elvishfiend** [comment] 2016-09-20 23:17
I think the problem is that you have `DetectColumnCountChanges = false` so when the number of columns changes, it doesn't have an issue with that.
Try setting it to `true` and see if that solves the problem.

**Comment by dennisverheijen** [comment] 2016-09-21 07:30
When I set `DetectColumnChanges` to `true` then `CsvReader.GetRecords<T>()` will throw an exception and abort reading alltogether. That's not what I'm looking for. 
I'm looking for a solution that will call the ReadingExceptionCallback in such a case, and then continues reading the next line.

**Comment by jamesbascle** [comment] 2016-09-21 07:45
You need to loop and do GetRecord inside of a try catch block to read each
row individually and handle any errors that occur.

GstRecords is intended go be a batch all or nothing operation.

**Comment by dennisverheijen** [comment] 2016-09-21 07:54
Thanks for the tip, I'll try that

**Comment by JoshClose** [comment] 2016-10-02 14:06
The reason for the confusion is `DetectColumnCountChanges` happens during a `Parser.Read()` and `ReadingExceptionCallback` happens after the field has been read, and it's being converted into a class object.

I think I'm going to move `DetectColumnCountChanges` into the reader. I don't see a reason the parser should throw an exception for that. If someone is using the parser directly, they'll already be looping (because there is no other way) and they can just check for themselves. The configuration is meant for when you have mappings and everything is happening for you automatically.

**Comment by JoshClose** [comment] 2016-10-02 17:33
It's moved into the reader and you can do both now. The fix is in version 3.0.

**Closed by JoshClose** 2016-10-02 17:33 UTC

**Comment by dennisverheijen** [comment] 2016-10-03 09:29
Thanks! Any idea when 3.0 will be on nuget (non-beta)?

**Comment by JoshClose** [comment] 2016-10-03 16:36
Hopefully soon. I want to do as much of the backlog as possible though to make sure there aren't any breaking changes that come up (like this was).

I'm hoping for no more than a month from now, but I do want a little time for it to stabilize. Once I go through the backlog and determine there shouldn't be any more breaking changes, I'll put out a release candidate and let it stabilize for a bit. There shouldn't be any breaking changes after the RC is out.
